version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    networks:
      - mynetwork

  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
